name: Release with Shell Script and Description

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.0.0

permissions:
  contents: write

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Previous and Current Tag
        run: |
          CURRENT_TAG="${GITHUB_REF#refs/tags/}"
          echo "CURRENT_TAG=$CURRENT_TAG" >> $GITHUB_ENV
          PREV_COMMIT=$(git rev-list --tags --skip=1 --max-count=1)
          if [ -n "$PREV_COMMIT" ]; then
            PREV_TAG=$(git describe --tags --abbrev=0 $PREV_COMMIT)
          else
            PREV_TAG=""
          fi
          echo "PREV_TAG=$PREV_TAG" >> $GITHUB_ENV

      - name: Generate Release Notes (in env var)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          declare -A USERMAP
          USERMAP["Attogram Project"]="attogram"
          
          CHANGES=""
          if [ -n "$PREV_TAG" ]; then
            COMMITS=$(git rev-list $PREV_TAG..$CURRENT_TAG)
          else
            COMMITS=$(git rev-list $CURRENT_TAG)
          fi

          for COMMIT in $COMMITS; do
            MSG=$(git log -1 --pretty=format:"%s" $COMMIT | cut -c1-80)
            SHORT_SHA=$(git rev-parse --short $COMMIT)
            AUTHOR_NAME=$(git log -1 --pretty=format:"%an" $COMMIT)
            AUTHOR_EMAIL=$(git log -1 --pretty=format:"%ae" $COMMIT)

            # Try hardcoded mapping first
            if [[ -n "${USERMAP[$AUTHOR_NAME]}" ]]; then
              GITHUB_USER="${USERMAP[$AUTHOR_NAME]}"
            else
              API_USER=$(curl -s -H "Authorization: token $GH_TOKEN" "https://api.github.com/search/users?q=${AUTHOR_EMAIL}+in:email" | jq -r '.items[0].login')
              if [[ "$API_USER" != "null" && -n "$API_USER" ]]; then
                GITHUB_USER="$API_USER"
              else
                GITHUB_USER=""
              fi
            fi

            if [[ -n "$GITHUB_USER" ]]; then
              AUTHOR_LINK="[${AUTHOR_NAME}](https://github.com/${GITHUB_USER})"
            else
              AUTHOR_LINK="${AUTHOR_NAME}"
            fi

            CHANGES+="- $SHORT_SHA by $AUTHOR_LINK: $MSG"$'\n'
          done

          if [ -n "$PREV_TAG" ]; then
            COMPARE_LINK="🔍 [View full diff](https://github.com/${{ github.repository }}/compare/$PREV_TAG...$CURRENT_TAG)"
          else
            COMPARE_LINK=""
          fi

          RELEASE_BODY="Ollama Bash Lib $CURRENT_TAG\n\nA Bash Library to interact with [Ollama](https://github.com/ollama/ollama)\n\nRepo: https://github.com/${{ github.repository }}\n\n## Changes\n\n${CHANGES}\n\n${COMPARE_LINK}"

          echo "RELEASENOTES<<EOF" >> $GITHUB_ENV
          echo -e "$RELEASE_BODY" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create GitHub Release with Script
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.CURRENT_TAG }}
          name: "Ollama Bash Lib ${{ env.CURRENT_TAG }}"
          body: ${{ env.RELEASENOTES }}
          files: ollama_bash_lib.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
